# Secvisogram Dependabot configuration file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    assignees:
      - "domachine"
    open-pull-requests-limit: 20
